About page
interclip/v4 pull request #125
Opened 2021-11-19 14:40 UTC by krystofex

- stats
- app links

2021-11-19 15:56 UTC, bigint requested changes

2021-11-19 15:56 UTC, bigint commented on src/pages/about.tsx
> +}): JSX.Element => {
React.ReactNode

2021-11-19 15:56 UTC, bigint commented on src/pages/about.tsx
> +}): JSX.Element => {
Also its good to use Interface for this!

2021-11-19 15:56 UTC, bigint commented on src/pages/about.tsx
> +}): JSX.Element => {
React.ReactNode

2021-11-19 15:56 UTC, bigint commented on src/pages/about.tsx
> +        <CountUp isCounting end={value} duration={1.4} />
😅  is this real?

2021-11-19 15:56 UTC, bigint commented on src/pages/about.tsx
> +      {title}
Wrap it to span or div 🙇🏻

2021-11-19 16:38 UTC, filiptronicek requested changes
I really like the updates, looks great. One thing that I am curious about is why have the cursor be a pointer on the facts? I don't see why this is needed, did you want to direct the user to some more info/link? 
https://github.com/interclip/interclip-next/blob/988792539e45700dccbe40a36efe3802b72a0959/src/pages/about.tsx#L118

2021-11-19 16:52 UTC, krystofex commented
Well I don't know really, where it should point to, it's just mistake haha

2021-11-28 17:27 UTC, filiptronicek commented
@krystofex could you please revisit this PR and take a look at @bigint's comments? Also, please, as per my comment remove the pointer cursor.

2021-11-28 21:51 UTC, filiptronicek commented
A bit sus @krystofex 

![image](https://user-images.githubusercontent.com/29888641/143787447-cfd6bb10-f691-45a7-bf07-f23fb9641500.png)

2022-01-13 11:12 UTC, filiptronicek commented
@krystofex are you still going to work on this or should I close this and implement it later?

2022-01-13 11:56 UTC, krystofex commented
I can finish it

2022-01-16 21:10 UTC, filiptronicek approved these changes
Great, thank you!

2023-07-16 20:18 UTC, closed without merging